### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by czhao2** [BorgwardtLab/P-WL#3]
I found the example code at ReadMe as below. However, the ***data*** folder is not under the ***src*** folder. Reported "Can't find file..."

$ cd src
$ python main.py -c -n 0 -p 1 data/MUTAG/*.gml -l data/MUTAG/Labels.txt

**Comment by czhao2** [comment]
After solving the path issue, I meet this problem. Thanks!

INFO:P-WL:Read 188 graphs and 188 labels
INFO:P-WL:Using cycle persistence
Traceback (most recent call last):
  File "main.py", line 284, in <module>
    main(args, logger)
  File "main.py", line 96, in main
    pwl.transform(graphs, args.num_iterations)
  File "/exp/home/usr/tools/P-WL/src/features.py", line 453, in transform
    X_per_iteration.append(pfg.fit_transform(weighted_graphs))
  File "/exp/home/usr/tools/P-WL/src/features.py", line 285, in fit_transform
    persistence_diagram, edge_indices_cycles = pdc.fit_transform(graph)
  File "/exp/home/usr/tools/P-WL/src/topology.py", line 214, in fit_transform
    edge_indices = np.argsort(edge_weights, kind='stable')
  File "/home/sur/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 940, in argsort
    return _wrapfunc(a, 'argsort', axis=axis, kind=kind, order=order)
  File "/home/usr/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: stable is an unrecognized kind of sort

**Comment by Pseudomanifold** [comment]
Thanks for raising this issue! It seems like your `numpy` installation is too old. Can you write a small script with the following content:

```python
import numpy as np


print(np.__version__)
```

Please paste the output here. The code requires at least version 1.15.0, in which the `stable` sorting option was added. See https://docs.scipy.org/doc/numpy/reference/generated/numpy.argsort.html for more details.

**Comment by czhao2** [comment]
Thank you for your quick reply! I have solved it.

**Comment by saiprasanna06** [comment]
I tried the example as given:   
$python main.py -c -n 0 -p 1 data/MUTAG/*.gml -l data/MUTAG/Labels.txt, with data in src folder. 

It gives following error:

OSError: [Errno 22] Invalid argument: 'data/MUTAG/*.gml'

**Comment by Pseudomanifold** [comment]
Are the graphs in the right place? If you specify `./data/MUTAG/*.gml` as the path, can does it work?

**Comment by saiprasanna06** [comment]
My current working directory is src
data is present in src/data


It gives following error:

OSError: [Errno 22] Invalid argument: './data/MUTAG/*.gml'

**Comment by Pseudomanifold** [comment]
Did you specify the `*`? What's the output of `ls ./data/MUTAG/*.gml`?

**Comment by saiprasanna06** [comment]
Yes, '*' is mntioned

> `ls ./data/MUTAG/*.gml`

Output is something like this
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        20-11-2022     13:01           1650 000.gml
-a----        20-11-2022     13:01           1262 001.gml
-a----        20-11-2022     13:01           1262 002.gml
-a----        20-11-2022     13:01           1916 003.gml
-a----        20-11-2022     13:01           1026 004.gml
-a----        20-11-2022     13:01           2739 005.gml
-a----        20-11-2022     13:01           1585 006.gml
-a----        20-11-2022     13:01           2017 007.gml
-a----        20-11-2022     13:01           1209 008.gml
-a----        20-11-2022     13:01           1735 009.gml
-a----        20-11-2022     13:01           1735 010.gml
-a----        20-11-2022     13:01           2073 011.gml
-a----        20-11-2022     13:01           2261 012.gml
-a----        20-11-2022     13:01           1303 013.gml
-a----        20-11-2022     13:01           1979 014.gml
-a----        20-11-2022     13:01           2261 015.gml
-a----        20-11-2022     13:01           1059 016.gml
-a----        20-11-2022     13:01           1735 017.gml
-a----        20-11-2022     13:01           1303 018.gml
-a----        20-11-2022     13:01           1829 019.gml
-a----        20-11-2022     13:01           1773 020.gml
-a----        20-11-2022     13:01           1735 021.gml
-a----        20-11-2022     13:01           2411 022.gml
-a----        20-11-2022     13:01           2899 023.gml
-a----        20-11-2022     13:01           1735 024.gml
-a----        20-11-2022     13:01           1247 025.gml
-a----        20-11-2022     13:01           2411 026.gml
-a----        20-11-2022     13:01           1735 027.gml
-a----        20-11-2022     13:01           2299 028.gml
-a----        20-11-2022     13:01           2411 029.gml
-a----        20-11-2022     13:01           2261 030.gml
-a----        20-11-2022     13:01           2337 031.gml

**Comment by saiprasanna06** [comment]
> Did you specify the `*`? What's the output of `ls ./data/MUTAG/*.gml`?

Yes, '*' is mentioned

**Comment by Pseudomanifold** [comment]
Can you try without additional parameters? 

```
$ python main.py data/MUTAG/*.gml -l data/MUTAG/Labels.txt
```
I am unable to reproduce your problem at the moment. Is there additional trace information in the output of the script? Which line fails exactly?

**Comment by saiprasanna06** [comment]
Traceback (most recent call last):
  File "D:\P-WL-master\src\main.py", line 284, in <module>
    main(args, logger)
  File "D:\P-WL-master\src\main.py", line 40, in main
    graphs = [ig.read(filename) for filename in args.FILES]
  File "D:\P-WL-master\src\main.py", line 40, in <listcomp>
    graphs = [ig.read(filename) for filename in args.FILES]
  File "C:\Users\msi\AppData\Local\Programs\Python\Python310\lib\site-packages\igraph\__init__.py", line 1015, in read
    return Graph.Read(filename, *args, **kwds)
  File "C:\Users\msi\AppData\Local\Programs\Python\Python310\lib\site-packages\igraph\io\files.py", line 295, in _construct_graph_from_file
    return reader(f, *args, **kwds)

OSError: [Errno 22] Invalid argument: './data/MUTAG/*.gml'

**Comment by Pseudomanifold** [comment]
This is a Windows machine. I have no clue why this fails in your case. Does it work without additional parameters? If not, try reading two graphs manually:

```
$ python main.py ./data/MUTAG/000.gml ./data/MUTAG/001.gml -l ./data/MUTAG/Labels.txt
```

This should result in an `AssertionError`.

**Comment by saiprasanna06** [comment]
> This is a Windows machine. I have no clue why this fails in your case. Does it work without additional parameters? If not, try reading two graphs manually:
> 
> ```
> $ python main.py ./data/MUTAG/000.gml ./data/MUTAG/001.gml -l ./data/MUTAG/Labels.txt
> ```
> 
> This should result in an `AssertionError`.

No, It does not work without additional parameters.

$ python main.py ./data/MUTAG/000.gml ./data/MUTAG/001.gml -l ./data/MUTAG/Labels.txt

Yes, This gives an AssertionError

**Comment by Pseudomanifold** [comment]
This means that Windows has trouble parsing the argument list—I don't understand why this is the case. Unfortunately, I have no clue how to solve this since I don't have a Windows machine available. I'd suggest to use a Linux machine to reproduce the results, or patch the loading code so that instead of requiring a list of graphs, a _directory_ can be specified. Hope that helps!

**Comment by saiprasanna06** [comment]
Sure, I shall try that. Thanks for your time and responses.

**Comment by saiprasanna06** [comment]
> This means that Windows has trouble parsing the argument list—I don't understand why this is the case. Unfortunately, I have no clue how to solve this since I don't have a Windows machine available. I'd suggest to use a Linux machine to reproduce the results, or patch the loading code so that instead of requiring a list of graphs, a _directory_ can be specified. Hope that helps!

Worked on a Ubuntu machine. thanks
